feat: use a log function

diff --git a/virtualboxbackup b/virtualboxbackup
--- a/virtualboxbackup
+++ b/virtualboxbackup
@@ -3,15 +3,30 @@
 # Name of the script
 SCRIPT_NAME="virtualboxbackup"
 
+# log function
+# $1: message
+# $2: level
+log() {
+    local message=$1
+    local level=$2
+
+    if [[ "$level" == "ERROR" ]]; then
+        echo "$(date) [ERROR] $message" >&2
+    else
+        echo "$(date) [INFO] $message"
+    fi
+}
+
+
 # Check if the output_dir exist and contains write permissions
 directory_valid(){
     if [[ ! -d "$1" ]]; then
-        echo "The directory $1 doesn't exist"
+        log "The directory $1 doesn't exist" "ERROR"
         exit 1
     fi
 
     if [[ ! -w "$1" ]]; then
-        echo "The directory $1 doesn't have write permissions"
+        log "The directory $1 doesn't have write permissions" "ERROR"
         exit 1
     fi
 }
@@ -19,7 +34,7 @@ directory_valid(){
 # Check if VBoxManage is installed
 vboxmanage_exist(){
     if ! command -v VBoxManage &> /dev/null; then
-        echo "VBoxManage is not installed"
+        log "VBoxManage is not installed" "ERROR"
         exit 1
     fi
 }
@@ -27,7 +42,7 @@ vboxmanage_exist(){
 # Check if the virtual machine exist
 vm_exist(){
     if ! VBoxManage list vms | grep -q "$1"; then
-        echo "The virtual machine $1 doesn't exist"
+        log "The virtual machine $1 doesn't exist" "ERROR"
         exit 1
     fi
 }
@@ -35,7 +50,7 @@ vm_exist(){
 # Check if the virtual machine is running
 vm_running(){
     if ! VBoxManage list runningvms | grep -q "$1"; then
-        echo "The virtual machine $1 is not running"
+        log "The virtual machine $1 is not running" "ERROR"
         exit 1
     fi
 }
@@ -70,28 +85,28 @@ virtualboxbackup__backup() {
             output_dir="$OPTARG"
             ;;
         \? )
-            echo "Invalid option: $OPTARG" 1>&2
+            log "Invalid option: $OPTARG" "ERROR"
             exit 1
             ;;
         : )
-            echo "Option $OPTARG require an argument" 1>&2
+            log "Option $OPTARG require an argument" "ERROR"
             exit 1
             ;;
     esac
     done
 
     if [[ -z "$job_name" ]]; then
-        echo "Must indicate the job name"
+        log "Must indicate the job name" "ERROR"
         exit 1
     fi
 
     if [[ -z "$vm_name" ]]; then
-        echo "Must indicate the virtual machine name"
+        log "Must indicate the virtual machine name" "ERROR"
         exit 1
     fi
 
     if [[ -z "$output_dir" ]]; then
-        echo "Must indicate the backup directory"
+        log "Must indicate the backup directory" "ERROR"
         exit 1
     fi
 
@@ -150,11 +165,11 @@ virtualboxbackup__schedule() {
             periodicity_value="$OPTARG"
             ;;
         \? )
-            echo "Invalid option: $OPTARG" 1>&2
+            log "Invalid option: $OPTARG" "ERROR"
             exit 1
             ;;
         : )
-            echo "Option $OPTARG require an argument" 1>&2
+            log "Option $OPTARG require an argument" "ERROR"
             exit 1
             ;;
     esac
@@ -162,22 +177,22 @@ virtualboxbackup__schedule() {
 
     # Validate the options
     if [[ -z "$job_name" ]]; then
-        echo "Must indicate the job name"
+        log "Must indicate the job name" "ERROR"
         exit 1
     fi
 
     if [[ -z "$vm_name" ]]; then
-        echo "Must indicate the virtual machine name"
+        log "Must indicate the virtual machine name" "ERROR"
         exit 1
     fi
 
     if [[ -z "$output_dir" ]]; then
-        echo "Must indicate the backup directory"
+        log "Must indicate the backup directory" "ERROR"
         exit 1
     fi
 
     if [[ -z "$periodicity_value" ]]; then
-        echo "Must indicate the periodicity in cronjob format"
+        log "Must indicate the periodicity in cronjob format" "ERROR"
         exit 1
     fi
 
@@ -195,7 +210,7 @@ virtualboxbackup__schedule() {
     # Check if the channel name already exists in the list
     if echo "$list" | grep -q "$job_name"; then
         # Show an error message and end the subcommand
-        echo "The job $job_name already exist."
+        log "The job $job_name already exist." "ERROR"
         return 2
     fi
 
@@ -223,18 +238,18 @@ virtualboxbackup__unschedule() {
             job_name="$OPTARG"
             ;;
         \? )
-            echo "Invalid option: $OPTARG" 1>&2
+            log "Invalid option: $OPTARG" "ERROR"
             exit 1
             ;;
         : )
-            echo "Option $OPTARG require an argument" 1>&2
+            log "Option $OPTARG require an argument" "ERROR"
             exit 1
             ;;
     esac
     done
 
     if [[ -z "$job_name" ]]; then
-        echo "Must indicate the job name"
+        log "Must indicate the job name" "ERROR"
         exit 1
     fi
 
@@ -244,8 +259,8 @@ virtualboxbackup__unschedule() {
     # Check if the channel name doesn't exist in the list
     if ! echo "$list" | grep -q "$job_name"; then
         # Show an error message and end the subcommand
-        echo "The job $job_name doesn't exists."
-        return 2
+        log "The job $job_name doesn't exists." "ERROR"
+        exit 1
     fi
 
     # Delete the job from the crontab
@@ -267,7 +282,7 @@ virtualboxbackup_launcher () {
         "virtualboxbackup__$cmd" "$@"
     else
         # Show an error message and end the subcommand
-        echo "Subcommand $cmd unknown" >&2
+        log "Subcommand $cmd unknown" "ERROR"
         exit 1
     fi
 }
